Watching for file changes with StatReloader
[12/May/2025 08:08:16] "GET /api/ HTTP/1.1" 200 183
[12/May/2025 08:08:18] "POST /api/auth/login/ HTTP/1.1" 200 561
Internal Server Error: /api/auth/registration/
Traceback (most recent call last):
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 331, in _query
    self._do_get_result(db)
    ~~~~~~~~~~~~~~~~~~~^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
    self._result = result = self._get_result()
                            ~~~~~~~~~~~~~~~~^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 363, in _get_result
    return self._get_db().store_result()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
MySQLdb.IntegrityError: (1062, "Duplicate entry 'test3@university.edu' for key 'email'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/dj_rest_auth/registration/views.py", line 42, in dispatch
    return super().dispatch(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/rest_framework/generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/dj_rest_auth/registration/views.py", line 64, in create
    user = self.perform_create(serializer)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/dj_rest_auth/registration/views.py", line 80, in perform_create
    user = serializer.save(self.request)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/dj_rest_auth/registration/serializers.py", line 277, in save
    user.save()
    ~~~~~~~~~^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/contrib/auth/base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/models/query.py", line 1854, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1881, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 331, in _query
    self._do_get_result(db)
    ~~~~~~~~~~~~~~~~~~~^^^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
    self._result = result = self._get_result()
                            ~~~~~~~~~~~~~~~~^^
  File "/home/lordkith/Venvs/UniBookSwap/lib/python3.13/site-packages/MySQLdb/cursors.py", line 363, in _get_result
    return self._get_db().store_result()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
django.db.utils.IntegrityError: (1062, "Duplicate entry 'test3@university.edu' for key 'email'")
[12/May/2025 08:08:18] "POST /api/auth/registration/ HTTP/1.1" 500 250397
[12/May/2025 08:08:18] "POST /api/books/ HTTP/1.1" 201 139
[12/May/2025 08:08:18] "GET /api/books/?search=CS101 HTTP/1.1" 200 421
